// grpcproc.cron.v1 is what grpcproc/cron's processes are called with, and
// the state they report for a successor to resume from.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/cron/v1/cron.proto

package cronv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control changes the jobs of a running cron process. Every op is a call,
// answered with google.protobuf.Empty or an error.
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Control_Add
	//	*Control_Remove
	//	*Control_Enable
	//	*Control_Disable
	Op            isControl_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_grpcproc_cron_v1_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_cron_v1_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_grpcproc_cron_v1_cron_proto_rawDescGZIP(), []int{0}
}

func (x *Control) GetOp() isControl_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Control) GetAdd() uint64 {
	if x != nil {
		if x, ok := x.Op.(*Control_Add); ok {
			return x.Add
		}
	}
	return 0
}

func (x *Control) GetRemove() string {
	if x != nil {
		if x, ok := x.Op.(*Control_Remove); ok {
			return x.Remove
		}
	}
	return ""
}

func (x *Control) GetEnable() string {
	if x != nil {
		if x, ok := x.Op.(*Control_Enable); ok {
			return x.Enable
		}
	}
	return ""
}

func (x *Control) GetDisable() string {
	if x != nil {
		if x, ok := x.Op.(*Control_Disable); ok {
			return x.Disable
		}
	}
	return ""
}

type isControl_Op interface {
	isControl_Op()
}

type Control_Add struct {
	// A job its caller registered in the cron package under this id. A
	// job holds Go functions, so only a cron process on the caller's node
	// can add it.
	Add uint64 `protobuf:"varint,1,opt,name=add,proto3,oneof"`
}

type Control_Remove struct {
	// The name of a job to remove. Runs already going go on.
	Remove string `protobuf:"bytes,2,opt,name=remove,proto3,oneof"`
}

type Control_Enable struct {
	// The name of a disabled job to run again on its schedule.
	Enable string `protobuf:"bytes,3,opt,name=enable,proto3,oneof"`
}

type Control_Disable struct {
	// The name of a job to keep but not run until it is enabled.
	Disable string `protobuf:"bytes,4,opt,name=disable,proto3,oneof"`
}

func (*Control_Add) isControl_Op() {}

func (*Control_Remove) isControl_Op() {}

func (*Control_Enable) isControl_Op() {}

func (*Control_Disable) isControl_Op() {}

// State is what a cron process remembers of its jobs: the time each last
// started a run, as scheduled. A cron process that resumes from it catches
// up on the runs missed since, as far as each job's starting deadline
// allows.
type State struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	LastRun       map[string]*timestamppb.Timestamp `protobuf:"bytes,1,rep,name=last_run,json=lastRun,proto3" json:"last_run,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_grpcproc_cron_v1_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_cron_v1_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_grpcproc_cron_v1_cron_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetLastRun() map[string]*timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

var File_grpcproc_cron_v1_cron_proto protoreflect.FileDescriptor

const file_grpcproc_cron_v1_cron_proto_rawDesc = "" +
	"\n" +
	"\x1bgrpcproc/cron/v1/cron.proto\x12\x10grpcproc.cron.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"s\n" +
	"\aControl\x12\x12\n" +
	"\x03add\x18\x01 \x01(\x04H\x00R\x03add\x12\x18\n" +
	"\x06remove\x18\x02 \x01(\tH\x00R\x06remove\x12\x18\n" +
	"\x06enable\x18\x03 \x01(\tH\x00R\x06enable\x12\x1a\n" +
	"\adisable\x18\x04 \x01(\tH\x00R\adisableB\x04\n" +
	"\x02op\"\xa0\x01\n" +
	"\x05State\x12?\n" +
	"\blast_run\x18\x01 \x03(\v2$.grpcproc.cron.v1.State.LastRunEntryR\alastRun\x1aV\n" +
	"\fLastRunEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05value:\x028\x01BBZ@github.com/floatdrop/grpcproc/cron/proto/grpcproc/cron/v1;cronv1b\x06proto3"

var (
	file_grpcproc_cron_v1_cron_proto_rawDescOnce sync.Once
	file_grpcproc_cron_v1_cron_proto_rawDescData []byte
)

func file_grpcproc_cron_v1_cron_proto_rawDescGZIP() []byte {
	file_grpcproc_cron_v1_cron_proto_rawDescOnce.Do(func() {
		file_grpcproc_cron_v1_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_cron_v1_cron_proto_rawDesc), len(file_grpcproc_cron_v1_cron_proto_rawDesc)))
	})
	return file_grpcproc_cron_v1_cron_proto_rawDescData
}

var file_grpcproc_cron_v1_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpcproc_cron_v1_cron_proto_goTypes = []any{
	(*Control)(nil),               // 0: grpcproc.cron.v1.Control
	(*State)(nil),                 // 1: grpcproc.cron.v1.State
	nil,                           // 2: grpcproc.cron.v1.State.LastRunEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_grpcproc_cron_v1_cron_proto_depIdxs = []int32{
	2, // 0: grpcproc.cron.v1.State.last_run:type_name -> grpcproc.cron.v1.State.LastRunEntry
	3, // 1: grpcproc.cron.v1.State.LastRunEntry.value:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcproc_cron_v1_cron_proto_init() }
func file_grpcproc_cron_v1_cron_proto_init() {
	if File_grpcproc_cron_v1_cron_proto != nil {
		return
	}
	file_grpcproc_cron_v1_cron_proto_msgTypes[0].OneofWrappers = []any{
		(*Control_Add)(nil),
		(*Control_Remove)(nil),
		(*Control_Enable)(nil),
		(*Control_Disable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_cron_v1_cron_proto_rawDesc), len(file_grpcproc_cron_v1_cron_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcproc_cron_v1_cron_proto_goTypes,
		DependencyIndexes: file_grpcproc_cron_v1_cron_proto_depIdxs,
		MessageInfos:      file_grpcproc_cron_v1_cron_proto_msgTypes,
	}.Build()
	File_grpcproc_cron_v1_cron_proto = out.File
	file_grpcproc_cron_v1_cron_proto_goTypes = nil
	file_grpcproc_cron_v1_cron_proto_depIdxs = nil
}
