// grpcproc.actor.v1 is what grpcproc/actor's supervisors are called with.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/actor/v1/actor.proto

package actorv1

import (
	v1 "github.com/floatdrop/grpcproc/proto/grpcproc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Control asks a supervisor to start a child, or to stop one.
type Control struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Control_Start
	//	*Control_Stop
	Op            isControl_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Control) Reset() {
	*x = Control{}
	mi := &file_grpcproc_actor_v1_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Control) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Control) ProtoMessage() {}

func (x *Control) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_actor_v1_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Control.ProtoReflect.Descriptor instead.
func (*Control) Descriptor() ([]byte, []int) {
	return file_grpcproc_actor_v1_actor_proto_rawDescGZIP(), []int{0}
}

func (x *Control) GetOp() isControl_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Control) GetStart() uint64 {
	if x != nil {
		if x, ok := x.Op.(*Control_Start); ok {
			return x.Start
		}
	}
	return 0
}

func (x *Control) GetStop() *v1.PID {
	if x != nil {
		if x, ok := x.Op.(*Control_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

type isControl_Op interface {
	isControl_Op()
}

type Control_Start struct {
	// A child spec its caller registered in the actor package under this
	// id. A spec holds Go functions, so only a supervisor on the caller's
	// node can start it.
	Start uint64 `protobuf:"varint,1,opt,name=start,proto3,oneof"`
}

type Control_Stop struct {
	// A running child to stop and forget.
	Stop *v1.PID `protobuf:"bytes,2,opt,name=stop,proto3,oneof"`
}

func (*Control_Start) isControl_Op() {}

func (*Control_Stop) isControl_Op() {}

var File_grpcproc_actor_v1_actor_proto protoreflect.FileDescriptor

const file_grpcproc_actor_v1_actor_proto_rawDesc = "" +
	"\n" +
	"\x1dgrpcproc/actor/v1/actor.proto\x12\x11grpcproc.actor.v1\x1a\x1agrpcproc/v1/grpcproc.proto\"O\n" +
	"\aControl\x12\x16\n" +
	"\x05start\x18\x01 \x01(\x04H\x00R\x05start\x12&\n" +
	"\x04stop\x18\x02 \x01(\v2\x10.grpcproc.v1.PIDH\x00R\x04stopB\x04\n" +
	"\x02opB?Z=github.com/floatdrop/grpcproc/proto/grpcproc/actor/v1;actorv1b\x06proto3"

var (
	file_grpcproc_actor_v1_actor_proto_rawDescOnce sync.Once
	file_grpcproc_actor_v1_actor_proto_rawDescData []byte
)

func file_grpcproc_actor_v1_actor_proto_rawDescGZIP() []byte {
	file_grpcproc_actor_v1_actor_proto_rawDescOnce.Do(func() {
		file_grpcproc_actor_v1_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_actor_v1_actor_proto_rawDesc), len(file_grpcproc_actor_v1_actor_proto_rawDesc)))
	})
	return file_grpcproc_actor_v1_actor_proto_rawDescData
}

var file_grpcproc_actor_v1_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpcproc_actor_v1_actor_proto_goTypes = []any{
	(*Control)(nil), // 0: grpcproc.actor.v1.Control
	(*v1.PID)(nil),  // 1: grpcproc.v1.PID
}
var file_grpcproc_actor_v1_actor_proto_depIdxs = []int32{
	1, // 0: grpcproc.actor.v1.Control.stop:type_name -> grpcproc.v1.PID
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpcproc_actor_v1_actor_proto_init() }
func file_grpcproc_actor_v1_actor_proto_init() {
	if File_grpcproc_actor_v1_actor_proto != nil {
		return
	}
	file_grpcproc_actor_v1_actor_proto_msgTypes[0].OneofWrappers = []any{
		(*Control_Start)(nil),
		(*Control_Stop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_actor_v1_actor_proto_rawDesc), len(file_grpcproc_actor_v1_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcproc_actor_v1_actor_proto_goTypes,
		DependencyIndexes: file_grpcproc_actor_v1_actor_proto_depIdxs,
		MessageInfos:      file_grpcproc_actor_v1_actor_proto_msgTypes,
	}.Build()
	File_grpcproc_actor_v1_actor_proto = out.File
	file_grpcproc_actor_v1_actor_proto_goTypes = nil
	file_grpcproc_actor_v1_actor_proto_depIdxs = nil
}
