// Messages of the blocking I/O example: what a connection's process takes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: connpb/conn.proto

package connpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event is everything a connection's process accepts. A mailbox holds one
// message type, so a line read from the connection is a message too, though
// it never leaves the node.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Event_Received
	//	*Event_Write
	//	*Event_Closed
	Kind          isEvent_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_connpb_conn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_connpb_conn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_connpb_conn_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetKind() isEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Event) GetReceived() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Received); ok {
			return x.Received
		}
	}
	return ""
}

func (x *Event) GetWrite() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Write); ok {
			return x.Write
		}
	}
	return ""
}

func (x *Event) GetClosed() string {
	if x != nil {
		if x, ok := x.Kind.(*Event_Closed); ok {
			return x.Closed
		}
	}
	return ""
}

type isEvent_Kind interface {
	isEvent_Kind()
}

type Event_Received struct {
	// A line the connection's reader read.
	Received string `protobuf:"bytes,1,opt,name=received,proto3,oneof"`
}

type Event_Write struct {
	// A line to write to the connection.
	Write string `protobuf:"bytes,2,opt,name=write,proto3,oneof"`
}

type Event_Closed struct {
	// Why the reader stopped: the peer is gone.
	Closed string `protobuf:"bytes,3,opt,name=closed,proto3,oneof"`
}

func (*Event_Received) isEvent_Kind() {}

func (*Event_Write) isEvent_Kind() {}

func (*Event_Closed) isEvent_Kind() {}

var File_connpb_conn_proto protoreflect.FileDescriptor

const file_connpb_conn_proto_rawDesc = "" +
	"\n" +
	"\x11connpb/conn.proto\x12\aconn.v1\"_\n" +
	"\x05Event\x12\x1c\n" +
	"\breceived\x18\x01 \x01(\tH\x00R\breceived\x12\x16\n" +
	"\x05write\x18\x02 \x01(\tH\x00R\x05write\x12\x18\n" +
	"\x06closed\x18\x03 \x01(\tH\x00R\x06closedB\x06\n" +
	"\x04kindB6Z4github.com/floatdrop/grpcproc/examples/connpb;connpbb\x06proto3"

var (
	file_connpb_conn_proto_rawDescOnce sync.Once
	file_connpb_conn_proto_rawDescData []byte
)

func file_connpb_conn_proto_rawDescGZIP() []byte {
	file_connpb_conn_proto_rawDescOnce.Do(func() {
		file_connpb_conn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connpb_conn_proto_rawDesc), len(file_connpb_conn_proto_rawDesc)))
	})
	return file_connpb_conn_proto_rawDescData
}

var file_connpb_conn_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_connpb_conn_proto_goTypes = []any{
	(*Event)(nil), // 0: conn.v1.Event
}
var file_connpb_conn_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_connpb_conn_proto_init() }
func file_connpb_conn_proto_init() {
	if File_connpb_conn_proto != nil {
		return
	}
	file_connpb_conn_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Received)(nil),
		(*Event_Write)(nil),
		(*Event_Closed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connpb_conn_proto_rawDesc), len(file_connpb_conn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connpb_conn_proto_goTypes,
		DependencyIndexes: file_connpb_conn_proto_depIdxs,
		MessageInfos:      file_connpb_conn_proto_msgTypes,
	}.Build()
	File_connpb_conn_proto = out.File
	file_connpb_conn_proto_goTypes = nil
	file_connpb_conn_proto_depIdxs = nil
}
