// The payments service's contract: its cashier answers charges.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/payments/v1/payments.proto

package paymentsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Charge takes amount from card for order. It is a call, answered with
// Charged.
type Charge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Card          string                 `protobuf:"bytes,2,opt,name=card,proto3" json:"card,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Charge) Reset() {
	*x = Charge{}
	mi := &file_guide_proto_payments_v1_payments_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Charge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Charge) ProtoMessage() {}

func (x *Charge) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_payments_v1_payments_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Charge.ProtoReflect.Descriptor instead.
func (*Charge) Descriptor() ([]byte, []int) {
	return file_guide_proto_payments_v1_payments_proto_rawDescGZIP(), []int{0}
}

func (x *Charge) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Charge) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

func (x *Charge) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Charged is the cashier's answer: a receipt, or why the card was declined.
// An error means the charge failed, and the card may or may not have been
// charged.
type Charged struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Receipt string                 `protobuf:"bytes,1,opt,name=receipt,proto3" json:"receipt,omitempty"`
	// Why the card was declined. Empty when it was charged.
	Declined      string `protobuf:"bytes,2,opt,name=declined,proto3" json:"declined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Charged) Reset() {
	*x = Charged{}
	mi := &file_guide_proto_payments_v1_payments_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Charged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Charged) ProtoMessage() {}

func (x *Charged) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_payments_v1_payments_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Charged.ProtoReflect.Descriptor instead.
func (*Charged) Descriptor() ([]byte, []int) {
	return file_guide_proto_payments_v1_payments_proto_rawDescGZIP(), []int{1}
}

func (x *Charged) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *Charged) GetDeclined() string {
	if x != nil {
		return x.Declined
	}
	return ""
}

var File_guide_proto_payments_v1_payments_proto protoreflect.FileDescriptor

const file_guide_proto_payments_v1_payments_proto_rawDesc = "" +
	"\n" +
	"&guide/proto/payments/v1/payments.proto\x12\vpayments.v1\"J\n" +
	"\x06Charge\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x12\n" +
	"\x04card\x18\x02 \x01(\tR\x04card\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"?\n" +
	"\aCharged\x12\x18\n" +
	"\areceipt\x18\x01 \x01(\tR\areceipt\x12\x1a\n" +
	"\bdeclined\x18\x02 \x01(\tR\bdeclinedBKZIgithub.com/floatdrop/grpcproc/examples/guide/proto/payments/v1;paymentsv1b\x06proto3"

var (
	file_guide_proto_payments_v1_payments_proto_rawDescOnce sync.Once
	file_guide_proto_payments_v1_payments_proto_rawDescData []byte
)

func file_guide_proto_payments_v1_payments_proto_rawDescGZIP() []byte {
	file_guide_proto_payments_v1_payments_proto_rawDescOnce.Do(func() {
		file_guide_proto_payments_v1_payments_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_payments_v1_payments_proto_rawDesc), len(file_guide_proto_payments_v1_payments_proto_rawDesc)))
	})
	return file_guide_proto_payments_v1_payments_proto_rawDescData
}

var file_guide_proto_payments_v1_payments_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guide_proto_payments_v1_payments_proto_goTypes = []any{
	(*Charge)(nil),  // 0: payments.v1.Charge
	(*Charged)(nil), // 1: payments.v1.Charged
}
var file_guide_proto_payments_v1_payments_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guide_proto_payments_v1_payments_proto_init() }
func file_guide_proto_payments_v1_payments_proto_init() {
	if File_guide_proto_payments_v1_payments_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_payments_v1_payments_proto_rawDesc), len(file_guide_proto_payments_v1_payments_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_payments_v1_payments_proto_goTypes,
		DependencyIndexes: file_guide_proto_payments_v1_payments_proto_depIdxs,
		MessageInfos:      file_guide_proto_payments_v1_payments_proto_msgTypes,
	}.Build()
	File_guide_proto_payments_v1_payments_proto = out.File
	file_guide_proto_payments_v1_payments_proto_goTypes = nil
	file_guide_proto_payments_v1_payments_proto_depIdxs = nil
}
