// The inventory service's contract: what its stock process accepts and
// answers. Another service depends on this package, never on the service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/inventory/v1/inventory.proto

package inventoryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command is everything the stock process accepts.
type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Command_Reserve
	//	*Command_Release
	Op            isCommand_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_guide_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() isCommand_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Command) GetReserve() *Reserve {
	if x != nil {
		if x, ok := x.Op.(*Command_Reserve); ok {
			return x.Reserve
		}
	}
	return nil
}

func (x *Command) GetRelease() *Release {
	if x != nil {
		if x, ok := x.Op.(*Command_Release); ok {
			return x.Release
		}
	}
	return nil
}

type isCommand_Op interface {
	isCommand_Op()
}

type Command_Reserve struct {
	// A call, answered with Reserved.
	Reserve *Reserve `protobuf:"bytes,1,opt,name=reserve,proto3,oneof"`
}

type Command_Release struct {
	// A send: gives back what a reservation took.
	Release *Release `protobuf:"bytes,2,opt,name=release,proto3,oneof"`
}

func (*Command_Reserve) isCommand_Op() {}

func (*Command_Release) isCommand_Op() {}

type Reserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserve) Reset() {
	*x = Reserve{}
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserve) ProtoMessage() {}

func (x *Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserve.ProtoReflect.Descriptor instead.
func (*Reserve) Descriptor() ([]byte, []int) {
	return file_guide_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *Reserve) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Reserve) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Reserve) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

// Reserved is the stock's answer: what is left, or why nothing was
// reserved. An error means the stock failed, not that it said no.
type Reserved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What is left of the sku after the reservation.
	Left int64 `protobuf:"varint,1,opt,name=left,proto3" json:"left,omitempty"`
	// Why nothing was reserved: not enough stock, say. Empty when it was.
	Refused       string `protobuf:"bytes,2,opt,name=refused,proto3" json:"refused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_guide_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *Reserved) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Reserved) GetRefused() string {
	if x != nil {
		return x.Refused
	}
	return ""
}

type Release struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,3,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_guide_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *Release) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Release) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Release) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

var File_guide_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_guide_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"(guide/proto/inventory/v1/inventory.proto\x12\finventory.v1\"u\n" +
	"\aCommand\x121\n" +
	"\areserve\x18\x01 \x01(\v2\x15.inventory.v1.ReserveH\x00R\areserve\x121\n" +
	"\arelease\x18\x02 \x01(\v2\x15.inventory.v1.ReleaseH\x00R\areleaseB\x04\n" +
	"\x02op\"C\n" +
	"\aReserve\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qty\"8\n" +
	"\bReserved\x12\x12\n" +
	"\x04left\x18\x01 \x01(\x03R\x04left\x12\x18\n" +
	"\arefused\x18\x02 \x01(\tR\arefused\"C\n" +
	"\aRelease\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x03 \x01(\x03R\x03qtyBMZKgithub.com/floatdrop/grpcproc/examples/guide/proto/inventory/v1;inventoryv1b\x06proto3"

var (
	file_guide_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_guide_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_guide_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_guide_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_guide_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_inventory_v1_inventory_proto_rawDesc), len(file_guide_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_guide_proto_inventory_v1_inventory_proto_rawDescData
}

var file_guide_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_guide_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*Command)(nil),  // 0: inventory.v1.Command
	(*Reserve)(nil),  // 1: inventory.v1.Reserve
	(*Reserved)(nil), // 2: inventory.v1.Reserved
	(*Release)(nil),  // 3: inventory.v1.Release
}
var file_guide_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	1, // 0: inventory.v1.Command.reserve:type_name -> inventory.v1.Reserve
	3, // 1: inventory.v1.Command.release:type_name -> inventory.v1.Release
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_guide_proto_inventory_v1_inventory_proto_init() }
func file_guide_proto_inventory_v1_inventory_proto_init() {
	if File_guide_proto_inventory_v1_inventory_proto != nil {
		return
	}
	file_guide_proto_inventory_v1_inventory_proto_msgTypes[0].OneofWrappers = []any{
		(*Command_Reserve)(nil),
		(*Command_Release)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_inventory_v1_inventory_proto_rawDesc), len(file_guide_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_guide_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_guide_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_guide_proto_inventory_v1_inventory_proto = out.File
	file_guide_proto_inventory_v1_inventory_proto_goTypes = nil
	file_guide_proto_inventory_v1_inventory_proto_depIdxs = nil
}
