// grpcproc.leader.v1 is what grpcproc/leader's electors say to each other,
// what they are called with, and what their own helper processes tell them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/leader/v1/leader.proto

package leaderv1

import (
	v1 "github.com/floatdrop/grpcproc/proto/grpcproc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Peer is a message from one elector to another of the same cluster. The
// sender's node is the node of the message's From.
type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sender's term. A receiver that is behind adopts it, and a leader
	// that is behind steps down.
	Term uint64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Peer_RequestVote
	//	*Peer_Vote
	//	*Peer_Heartbeat
	//	*Peer_Ack
	//	*Peer_TimeoutNow
	//	*Peer_Hello
	Kind          isPeer_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{0}
}

func (x *Peer) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Peer) GetKind() isPeer_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Peer) GetRequestVote() *RequestVote {
	if x != nil {
		if x, ok := x.Kind.(*Peer_RequestVote); ok {
			return x.RequestVote
		}
	}
	return nil
}

func (x *Peer) GetVote() *Vote {
	if x != nil {
		if x, ok := x.Kind.(*Peer_Vote); ok {
			return x.Vote
		}
	}
	return nil
}

func (x *Peer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Kind.(*Peer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Peer) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Kind.(*Peer_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *Peer) GetTimeoutNow() *TimeoutNow {
	if x != nil {
		if x, ok := x.Kind.(*Peer_TimeoutNow); ok {
			return x.TimeoutNow
		}
	}
	return nil
}

func (x *Peer) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Kind.(*Peer_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

type isPeer_Kind interface {
	isPeer_Kind()
}

type Peer_RequestVote struct {
	RequestVote *RequestVote `protobuf:"bytes,2,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type Peer_Vote struct {
	Vote *Vote `protobuf:"bytes,3,opt,name=vote,proto3,oneof"`
}

type Peer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type Peer_Ack struct {
	Ack *Ack `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type Peer_TimeoutNow struct {
	TimeoutNow *TimeoutNow `protobuf:"bytes,6,opt,name=timeout_now,json=timeoutNow,proto3,oneof"`
}

type Peer_Hello struct {
	Hello *Hello `protobuf:"bytes,7,opt,name=hello,proto3,oneof"`
}

func (*Peer_RequestVote) isPeer_Kind() {}

func (*Peer_Vote) isPeer_Kind() {}

func (*Peer_Heartbeat) isPeer_Kind() {}

func (*Peer_Ack) isPeer_Kind() {}

func (*Peer_TimeoutNow) isPeer_Kind() {}

func (*Peer_Hello) isPeer_Kind() {}

// Hello makes the sender known to the receiver, which answers with a
// reply: a node greets the nodes it has not heard from, and hears back from
// those it can reach.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         bool                   `protobuf:"varint,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetReply() bool {
	if x != nil {
		return x.Reply
	}
	return false
}

// Version orders the states electors hold: by the term of the leader that
// made it, then by the order that leader made them in.
type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{2}
}

func (x *Version) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Version) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// State is a leader's state as its electors hold it.
type State struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Unset until a leader has checkpointed.
	Value *anypb.Any `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	// The nodes that may not lead, sorted: they do not campaign, voters
	// refuse them, and a leader among them hands over.
	Cordoned      []string `protobuf:"bytes,3,rep,name=cordoned,proto3" json:"cordoned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{3}
}

func (x *State) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *State) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *State) GetCordoned() []string {
	if x != nil {
		return x.Cordoned
	}
	return nil
}

// Kept is what an elector keeps in its Spec.Store, and starts from again:
// Raft's persistent state, whose log is the one State.
type Kept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Term  uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// The node this one voted for in the term, if any.
	VotedFor      string `protobuf:"bytes,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	State         *State `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kept) Reset() {
	*x = Kept{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kept) ProtoMessage() {}

func (x *Kept) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kept.ProtoReflect.Descriptor instead.
func (*Kept) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{4}
}

func (x *Kept) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Kept) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

func (x *Kept) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// RequestVote asks for a vote in the term, from a candidate holding the
// state of this version. A voter holding a newer one refuses it.
type RequestVote struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Version *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Set when the leader handed over to the candidate: voters that heard
	// from that leader lately vote all the same.
	Transfer bool `protobuf:"varint,2,opt,name=transfer,proto3" json:"transfer,omitempty"`
	// Set for a pre-vote: would the voter vote in the term, which the
	// candidate has not begun? Nobody's term changes, and nobody votes, so a
	// node cut off from the others cannot raise its term while it is, and
	// depose the leader with it when it is back.
	Pre           bool `protobuf:"varint,3,opt,name=pre,proto3" json:"pre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVote) Reset() {
	*x = RequestVote{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVote) ProtoMessage() {}

func (x *RequestVote) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVote.ProtoReflect.Descriptor instead.
func (*RequestVote) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVote) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *RequestVote) GetTransfer() bool {
	if x != nil {
		return x.Transfer
	}
	return false
}

func (x *RequestVote) GetPre() bool {
	if x != nil {
		return x.Pre
	}
	return false
}

// Vote answers a RequestVote of the same term, and pre-vote.
type Vote struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Granted bool                   `protobuf:"varint,1,opt,name=granted,proto3" json:"granted,omitempty"`
	Pre     bool                   `protobuf:"varint,2,opt,name=pre,proto3" json:"pre,omitempty"`
	// Set when the vote is refused for the candidate's older state: the
	// voter's, for the candidate to take and campaign again with. A node
	// that restarted, and holds nothing, catches up this way even while no
	// leader sends it the state.
	State         *State `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vote) Reset() {
	*x = Vote{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vote) ProtoMessage() {}

func (x *Vote) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vote.ProtoReflect.Descriptor instead.
func (*Vote) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{6}
}

func (x *Vote) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

func (x *Vote) GetPre() bool {
	if x != nil {
		return x.Pre
	}
	return false
}

func (x *Vote) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// Heartbeat asserts the sender's leadership for the term.
type Heartbeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set while the follower's last Ack showed another version than the
	// leader's: the follower takes it as its own.
	State         *State `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{7}
}

func (x *Heartbeat) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

// Ack answers a Heartbeat, with the version the follower now holds.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *Version               `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

// TimeoutNow is a leader handing over: its receiver campaigns at once.
type TimeoutNow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeoutNow) Reset() {
	*x = TimeoutNow{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeoutNow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeoutNow) ProtoMessage() {}

func (x *TimeoutNow) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeoutNow.ProtoReflect.Descriptor instead.
func (*TimeoutNow) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{9}
}

// Checkpoint is a leader's singleton's state, for its elector to replicate:
// a call, answered with google.protobuf.Empty once a majority of the
// cluster holds it, or an error if the term is over.
type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	State         *anypb.Any             `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{10}
}

func (x *Checkpoint) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Checkpoint) GetState() *anypb.Any {
	if x != nil {
		return x.State
	}
	return nil
}

// StatusRequest asks an elector for its Status.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{11}
}

// Status is what an elector believes.
type Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Role  string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Term  uint64                 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// The leader's node, or empty while none is known.
	Leader string `protobuf:"bytes,3,opt,name=leader,proto3" json:"leader,omitempty"`
	// The nodes whose majority elects a leader, this one included.
	View    []string `protobuf:"bytes,4,rep,name=view,proto3" json:"view,omitempty"`
	Quorum  uint32   `protobuf:"varint,5,opt,name=quorum,proto3" json:"quorum,omitempty"`
	Version *Version `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// The singleton, on the leader, once it runs.
	Singleton *v1.PID `protobuf:"bytes,7,opt,name=singleton,proto3" json:"singleton,omitempty"`
	// The nodes that may not lead.
	Cordoned      []string `protobuf:"bytes,8,rep,name=cordoned,proto3" json:"cordoned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{12}
}

func (x *Status) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Status) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Status) GetLeader() string {
	if x != nil {
		return x.Leader
	}
	return ""
}

func (x *Status) GetView() []string {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *Status) GetQuorum() uint32 {
	if x != nil {
		return x.Quorum
	}
	return 0
}

func (x *Status) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *Status) GetSingleton() *v1.PID {
	if x != nil {
		return x.Singleton
	}
	return nil
}

func (x *Status) GetCordoned() []string {
	if x != nil {
		return x.Cordoned
	}
	return nil
}

// Resign asks a leader to hand over to a follower, and answers, with
// google.protobuf.Empty, once it has.
type Resign struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The follower to hand over to; empty for the one with the latest state.
	To            string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resign) Reset() {
	*x = Resign{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resign) ProtoMessage() {}

func (x *Resign) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resign.ProtoReflect.Descriptor instead.
func (*Resign) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{13}
}

func (x *Resign) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// Cordon asks a leader to keep a node from leading, or, with off, to let
// it lead again: a call, answered with google.protobuf.Empty once a
// majority of the cluster holds the change.
type Cordon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Off           bool                   `protobuf:"varint,2,opt,name=off,proto3" json:"off,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cordon) Reset() {
	*x = Cordon{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cordon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cordon) ProtoMessage() {}

func (x *Cordon) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cordon.ProtoReflect.Descriptor instead.
func (*Cordon) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{14}
}

func (x *Cordon) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Cordon) GetOff() bool {
	if x != nil {
		return x.Off
	}
	return false
}

// PeerDown is a relay telling its elector that the peer's elector it
// monitors is gone, with the Down's reason.
type PeerDown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerDown) Reset() {
	*x = PeerDown{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerDown) ProtoMessage() {}

func (x *PeerDown) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerDown.ProtoReflect.Descriptor instead.
func (*PeerDown) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{15}
}

func (x *PeerDown) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PeerDown) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Watch tells a relay to monitor its peer's elector again.
type Watch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Watch) Reset() {
	*x = Watch{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Watch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Watch) ProtoMessage() {}

func (x *Watch) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Watch.ProtoReflect.Descriptor instead.
func (*Watch) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{16}
}

// MemberEvent is the membership bridge telling its elector of a node
// joining or leaving the grpcproc cluster.
type MemberEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          string                 `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	Up            bool                   `protobuf:"varint,2,opt,name=up,proto3" json:"up,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberEvent) Reset() {
	*x = MemberEvent{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberEvent) ProtoMessage() {}

func (x *MemberEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberEvent.ProtoReflect.Descriptor instead.
func (*MemberEvent) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{17}
}

func (x *MemberEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *MemberEvent) GetUp() bool {
	if x != nil {
		return x.Up
	}
	return false
}

// Started is a starter telling its elector how starting the singleton of
// the term went: its PID, or why it did not start.
type Started struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Pid           *v1.PID                `protobuf:"bytes,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Started) Reset() {
	*x = Started{}
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Started) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Started) ProtoMessage() {}

func (x *Started) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_leader_v1_leader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Started.ProtoReflect.Descriptor instead.
func (*Started) Descriptor() ([]byte, []int) {
	return file_grpcproc_leader_v1_leader_proto_rawDescGZIP(), []int{18}
}

func (x *Started) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Started) GetPid() *v1.PID {
	if x != nil {
		return x.Pid
	}
	return nil
}

func (x *Started) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_grpcproc_leader_v1_leader_proto protoreflect.FileDescriptor

const file_grpcproc_leader_v1_leader_proto_rawDesc = "" +
	"\n" +
	"\x1fgrpcproc/leader/v1/leader.proto\x12\x12grpcproc.leader.v1\x1a\x19google/protobuf/any.proto\x1a\x1agrpcproc/v1/grpcproc.proto\"\xfa\x02\n" +
	"\x04Peer\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12D\n" +
	"\frequest_vote\x18\x02 \x01(\v2\x1f.grpcproc.leader.v1.RequestVoteH\x00R\vrequestVote\x12.\n" +
	"\x04vote\x18\x03 \x01(\v2\x18.grpcproc.leader.v1.VoteH\x00R\x04vote\x12=\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1d.grpcproc.leader.v1.HeartbeatH\x00R\theartbeat\x12+\n" +
	"\x03ack\x18\x05 \x01(\v2\x17.grpcproc.leader.v1.AckH\x00R\x03ack\x12A\n" +
	"\vtimeout_now\x18\x06 \x01(\v2\x1e.grpcproc.leader.v1.TimeoutNowH\x00R\n" +
	"timeoutNow\x121\n" +
	"\x05hello\x18\a \x01(\v2\x19.grpcproc.leader.v1.HelloH\x00R\x05helloB\x06\n" +
	"\x04kind\"\x1d\n" +
	"\x05Hello\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\bR\x05reply\"/\n" +
	"\aVersion\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\"\x86\x01\n" +
	"\x05State\x125\n" +
	"\aversion\x18\x01 \x01(\v2\x1b.grpcproc.leader.v1.VersionR\aversion\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\x12\x1a\n" +
	"\bcordoned\x18\x03 \x03(\tR\bcordoned\"h\n" +
	"\x04Kept\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\tR\bvotedFor\x12/\n" +
	"\x05state\x18\x03 \x01(\v2\x19.grpcproc.leader.v1.StateR\x05state\"r\n" +
	"\vRequestVote\x125\n" +
	"\aversion\x18\x01 \x01(\v2\x1b.grpcproc.leader.v1.VersionR\aversion\x12\x1a\n" +
	"\btransfer\x18\x02 \x01(\bR\btransfer\x12\x10\n" +
	"\x03pre\x18\x03 \x01(\bR\x03pre\"c\n" +
	"\x04Vote\x12\x18\n" +
	"\agranted\x18\x01 \x01(\bR\agranted\x12\x10\n" +
	"\x03pre\x18\x02 \x01(\bR\x03pre\x12/\n" +
	"\x05state\x18\x03 \x01(\v2\x19.grpcproc.leader.v1.StateR\x05state\"<\n" +
	"\tHeartbeat\x12/\n" +
	"\x05state\x18\x01 \x01(\v2\x19.grpcproc.leader.v1.StateR\x05state\"<\n" +
	"\x03Ack\x125\n" +
	"\aversion\x18\x01 \x01(\v2\x1b.grpcproc.leader.v1.VersionR\aversion\"\f\n" +
	"\n" +
	"TimeoutNow\"L\n" +
	"\n" +
	"Checkpoint\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12*\n" +
	"\x05state\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05state\"\x0f\n" +
	"\rStatusRequest\"\xf7\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x04R\x04term\x12\x16\n" +
	"\x06leader\x18\x03 \x01(\tR\x06leader\x12\x12\n" +
	"\x04view\x18\x04 \x03(\tR\x04view\x12\x16\n" +
	"\x06quorum\x18\x05 \x01(\rR\x06quorum\x125\n" +
	"\aversion\x18\x06 \x01(\v2\x1b.grpcproc.leader.v1.VersionR\aversion\x12.\n" +
	"\tsingleton\x18\a \x01(\v2\x10.grpcproc.v1.PIDR\tsingleton\x12\x1a\n" +
	"\bcordoned\x18\b \x03(\tR\bcordoned\"\x18\n" +
	"\x06Resign\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\".\n" +
	"\x06Cordon\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x10\n" +
	"\x03off\x18\x02 \x01(\bR\x03off\"6\n" +
	"\bPeerDown\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\a\n" +
	"\x05Watch\"1\n" +
	"\vMemberEvent\x12\x12\n" +
	"\x04node\x18\x01 \x01(\tR\x04node\x12\x0e\n" +
	"\x02up\x18\x02 \x01(\bR\x02up\"W\n" +
	"\aStarted\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\"\n" +
	"\x03pid\x18\x02 \x01(\v2\x10.grpcproc.v1.PIDR\x03pid\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorBHZFgithub.com/floatdrop/grpcproc/leader/proto/grpcproc/leader/v1;leaderv1b\x06proto3"

var (
	file_grpcproc_leader_v1_leader_proto_rawDescOnce sync.Once
	file_grpcproc_leader_v1_leader_proto_rawDescData []byte
)

func file_grpcproc_leader_v1_leader_proto_rawDescGZIP() []byte {
	file_grpcproc_leader_v1_leader_proto_rawDescOnce.Do(func() {
		file_grpcproc_leader_v1_leader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_leader_v1_leader_proto_rawDesc), len(file_grpcproc_leader_v1_leader_proto_rawDesc)))
	})
	return file_grpcproc_leader_v1_leader_proto_rawDescData
}

var file_grpcproc_leader_v1_leader_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_grpcproc_leader_v1_leader_proto_goTypes = []any{
	(*Peer)(nil),          // 0: grpcproc.leader.v1.Peer
	(*Hello)(nil),         // 1: grpcproc.leader.v1.Hello
	(*Version)(nil),       // 2: grpcproc.leader.v1.Version
	(*State)(nil),         // 3: grpcproc.leader.v1.State
	(*Kept)(nil),          // 4: grpcproc.leader.v1.Kept
	(*RequestVote)(nil),   // 5: grpcproc.leader.v1.RequestVote
	(*Vote)(nil),          // 6: grpcproc.leader.v1.Vote
	(*Heartbeat)(nil),     // 7: grpcproc.leader.v1.Heartbeat
	(*Ack)(nil),           // 8: grpcproc.leader.v1.Ack
	(*TimeoutNow)(nil),    // 9: grpcproc.leader.v1.TimeoutNow
	(*Checkpoint)(nil),    // 10: grpcproc.leader.v1.Checkpoint
	(*StatusRequest)(nil), // 11: grpcproc.leader.v1.StatusRequest
	(*Status)(nil),        // 12: grpcproc.leader.v1.Status
	(*Resign)(nil),        // 13: grpcproc.leader.v1.Resign
	(*Cordon)(nil),        // 14: grpcproc.leader.v1.Cordon
	(*PeerDown)(nil),      // 15: grpcproc.leader.v1.PeerDown
	(*Watch)(nil),         // 16: grpcproc.leader.v1.Watch
	(*MemberEvent)(nil),   // 17: grpcproc.leader.v1.MemberEvent
	(*Started)(nil),       // 18: grpcproc.leader.v1.Started
	(*anypb.Any)(nil),     // 19: google.protobuf.Any
	(*v1.PID)(nil),        // 20: grpcproc.v1.PID
}
var file_grpcproc_leader_v1_leader_proto_depIdxs = []int32{
	5,  // 0: grpcproc.leader.v1.Peer.request_vote:type_name -> grpcproc.leader.v1.RequestVote
	6,  // 1: grpcproc.leader.v1.Peer.vote:type_name -> grpcproc.leader.v1.Vote
	7,  // 2: grpcproc.leader.v1.Peer.heartbeat:type_name -> grpcproc.leader.v1.Heartbeat
	8,  // 3: grpcproc.leader.v1.Peer.ack:type_name -> grpcproc.leader.v1.Ack
	9,  // 4: grpcproc.leader.v1.Peer.timeout_now:type_name -> grpcproc.leader.v1.TimeoutNow
	1,  // 5: grpcproc.leader.v1.Peer.hello:type_name -> grpcproc.leader.v1.Hello
	2,  // 6: grpcproc.leader.v1.State.version:type_name -> grpcproc.leader.v1.Version
	19, // 7: grpcproc.leader.v1.State.value:type_name -> google.protobuf.Any
	3,  // 8: grpcproc.leader.v1.Kept.state:type_name -> grpcproc.leader.v1.State
	2,  // 9: grpcproc.leader.v1.RequestVote.version:type_name -> grpcproc.leader.v1.Version
	3,  // 10: grpcproc.leader.v1.Vote.state:type_name -> grpcproc.leader.v1.State
	3,  // 11: grpcproc.leader.v1.Heartbeat.state:type_name -> grpcproc.leader.v1.State
	2,  // 12: grpcproc.leader.v1.Ack.version:type_name -> grpcproc.leader.v1.Version
	19, // 13: grpcproc.leader.v1.Checkpoint.state:type_name -> google.protobuf.Any
	2,  // 14: grpcproc.leader.v1.Status.version:type_name -> grpcproc.leader.v1.Version
	20, // 15: grpcproc.leader.v1.Status.singleton:type_name -> grpcproc.v1.PID
	20, // 16: grpcproc.leader.v1.Started.pid:type_name -> grpcproc.v1.PID
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_grpcproc_leader_v1_leader_proto_init() }
func file_grpcproc_leader_v1_leader_proto_init() {
	if File_grpcproc_leader_v1_leader_proto != nil {
		return
	}
	file_grpcproc_leader_v1_leader_proto_msgTypes[0].OneofWrappers = []any{
		(*Peer_RequestVote)(nil),
		(*Peer_Vote)(nil),
		(*Peer_Heartbeat)(nil),
		(*Peer_Ack)(nil),
		(*Peer_TimeoutNow)(nil),
		(*Peer_Hello)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_leader_v1_leader_proto_rawDesc), len(file_grpcproc_leader_v1_leader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcproc_leader_v1_leader_proto_goTypes,
		DependencyIndexes: file_grpcproc_leader_v1_leader_proto_depIdxs,
		MessageInfos:      file_grpcproc_leader_v1_leader_proto_msgTypes,
	}.Build()
	File_grpcproc_leader_v1_leader_proto = out.File
	file_grpcproc_leader_v1_leader_proto_goTypes = nil
	file_grpcproc_leader_v1_leader_proto_depIdxs = nil
}
