// Messages of the examples: a shop with a stock of items.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: shoppb/shop.proto

package shoppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reserve asks for qty items of sku. The answer is Reserved.
type Reserve struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserve) Reset() {
	*x = Reserve{}
	mi := &file_shoppb_shop_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserve) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserve) ProtoMessage() {}

func (x *Reserve) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserve.ProtoReflect.Descriptor instead.
func (*Reserve) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{0}
}

func (x *Reserve) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Reserve) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

// Reserved is what is left of sku after a reservation.
type Reserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Left          int64                  `protobuf:"varint,2,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reserved) Reset() {
	*x = Reserved{}
	mi := &file_shoppb_shop_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reserved) ProtoMessage() {}

func (x *Reserved) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reserved.ProtoReflect.Descriptor instead.
func (*Reserved) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{1}
}

func (x *Reserved) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Reserved) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

// Restock adds qty items of sku.
type Restock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restock) Reset() {
	*x = Restock{}
	mi := &file_shoppb_shop_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restock) ProtoMessage() {}

func (x *Restock) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restock.ProtoReflect.Descriptor instead.
func (*Restock) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{2}
}

func (x *Restock) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Restock) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

// Stock is everything a stock process accepts. A mailbox holds one message
// type; a oneof lets it carry several operations.
type Stock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*Stock_Reserve
	//	*Stock_Restock
	Op            isStock_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stock) Reset() {
	*x = Stock{}
	mi := &file_shoppb_shop_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stock) ProtoMessage() {}

func (x *Stock) ProtoReflect() protoreflect.Message {
	mi := &file_shoppb_shop_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stock.ProtoReflect.Descriptor instead.
func (*Stock) Descriptor() ([]byte, []int) {
	return file_shoppb_shop_proto_rawDescGZIP(), []int{3}
}

func (x *Stock) GetOp() isStock_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *Stock) GetReserve() *Reserve {
	if x != nil {
		if x, ok := x.Op.(*Stock_Reserve); ok {
			return x.Reserve
		}
	}
	return nil
}

func (x *Stock) GetRestock() *Restock {
	if x != nil {
		if x, ok := x.Op.(*Stock_Restock); ok {
			return x.Restock
		}
	}
	return nil
}

type isStock_Op interface {
	isStock_Op()
}

type Stock_Reserve struct {
	Reserve *Reserve `protobuf:"bytes,1,opt,name=reserve,proto3,oneof"`
}

type Stock_Restock struct {
	Restock *Restock `protobuf:"bytes,2,opt,name=restock,proto3,oneof"`
}

func (*Stock_Reserve) isStock_Op() {}

func (*Stock_Restock) isStock_Op() {}

var File_shoppb_shop_proto protoreflect.FileDescriptor

const file_shoppb_shop_proto_rawDesc = "" +
	"\n" +
	"\x11shoppb/shop.proto\x12\ashop.v1\"-\n" +
	"\aReserve\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\"0\n" +
	"\bReserved\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x12\n" +
	"\x04left\x18\x02 \x01(\x03R\x04left\"-\n" +
	"\aRestock\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\"i\n" +
	"\x05Stock\x12,\n" +
	"\areserve\x18\x01 \x01(\v2\x10.shop.v1.ReserveH\x00R\areserve\x12,\n" +
	"\arestock\x18\x02 \x01(\v2\x10.shop.v1.RestockH\x00R\arestockB\x04\n" +
	"\x02opB6Z4github.com/floatdrop/grpcproc/examples/shoppb;shoppbb\x06proto3"

var (
	file_shoppb_shop_proto_rawDescOnce sync.Once
	file_shoppb_shop_proto_rawDescData []byte
)

func file_shoppb_shop_proto_rawDescGZIP() []byte {
	file_shoppb_shop_proto_rawDescOnce.Do(func() {
		file_shoppb_shop_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shoppb_shop_proto_rawDesc), len(file_shoppb_shop_proto_rawDesc)))
	})
	return file_shoppb_shop_proto_rawDescData
}

var file_shoppb_shop_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shoppb_shop_proto_goTypes = []any{
	(*Reserve)(nil),  // 0: shop.v1.Reserve
	(*Reserved)(nil), // 1: shop.v1.Reserved
	(*Restock)(nil),  // 2: shop.v1.Restock
	(*Stock)(nil),    // 3: shop.v1.Stock
}
var file_shoppb_shop_proto_depIdxs = []int32{
	0, // 0: shop.v1.Stock.reserve:type_name -> shop.v1.Reserve
	2, // 1: shop.v1.Stock.restock:type_name -> shop.v1.Restock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_shoppb_shop_proto_init() }
func file_shoppb_shop_proto_init() {
	if File_shoppb_shop_proto != nil {
		return
	}
	file_shoppb_shop_proto_msgTypes[3].OneofWrappers = []any{
		(*Stock_Reserve)(nil),
		(*Stock_Restock)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shoppb_shop_proto_rawDesc), len(file_shoppb_shop_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shoppb_shop_proto_goTypes,
		DependencyIndexes: file_shoppb_shop_proto_depIdxs,
		MessageInfos:      file_shoppb_shop_proto_msgTypes,
	}.Build()
	File_shoppb_shop_proto = out.File
	file_shoppb_shop_proto_goTypes = nil
	file_shoppb_shop_proto_depIdxs = nil
}
