// The orders service's contract: its desk takes orders.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: guide/proto/orders/v1/orders.proto

package ordersv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Place orders qty of sku, paid with card. It is a call, answered with
// Placed. An error means no answer: the desk could not reach a service it
// depends on, or not in time.
type Place struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Qty           int64                  `protobuf:"varint,2,opt,name=qty,proto3" json:"qty,omitempty"`
	Card          string                 `protobuf:"bytes,3,opt,name=card,proto3" json:"card,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Place) Reset() {
	*x = Place{}
	mi := &file_guide_proto_orders_v1_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Place) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Place) ProtoMessage() {}

func (x *Place) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_orders_v1_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Place.ProtoReflect.Descriptor instead.
func (*Place) Descriptor() ([]byte, []int) {
	return file_guide_proto_orders_v1_orders_proto_rawDescGZIP(), []int{0}
}

func (x *Place) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *Place) GetQty() int64 {
	if x != nil {
		return x.Qty
	}
	return 0
}

func (x *Place) GetCard() string {
	if x != nil {
		return x.Card
	}
	return ""
}

// Placed is the desk's answer: the order, or why it was refused.
type Placed struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Order   string                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Receipt string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	// What is left of the sku once the order is placed.
	Left int64 `protobuf:"varint,3,opt,name=left,proto3" json:"left,omitempty"`
	// Why the order was refused: the item, the stock or the card. Empty when
	// it was placed.
	Refused       string `protobuf:"bytes,4,opt,name=refused,proto3" json:"refused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Placed) Reset() {
	*x = Placed{}
	mi := &file_guide_proto_orders_v1_orders_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Placed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Placed) ProtoMessage() {}

func (x *Placed) ProtoReflect() protoreflect.Message {
	mi := &file_guide_proto_orders_v1_orders_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Placed.ProtoReflect.Descriptor instead.
func (*Placed) Descriptor() ([]byte, []int) {
	return file_guide_proto_orders_v1_orders_proto_rawDescGZIP(), []int{1}
}

func (x *Placed) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Placed) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *Placed) GetLeft() int64 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *Placed) GetRefused() string {
	if x != nil {
		return x.Refused
	}
	return ""
}

var File_guide_proto_orders_v1_orders_proto protoreflect.FileDescriptor

const file_guide_proto_orders_v1_orders_proto_rawDesc = "" +
	"\n" +
	"\"guide/proto/orders/v1/orders.proto\x12\torders.v1\"?\n" +
	"\x05Place\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x10\n" +
	"\x03qty\x18\x02 \x01(\x03R\x03qty\x12\x12\n" +
	"\x04card\x18\x03 \x01(\tR\x04card\"f\n" +
	"\x06Placed\x12\x14\n" +
	"\x05order\x18\x01 \x01(\tR\x05order\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\x12\x12\n" +
	"\x04left\x18\x03 \x01(\x03R\x04left\x12\x18\n" +
	"\arefused\x18\x04 \x01(\tR\arefusedBGZEgithub.com/floatdrop/grpcproc/examples/guide/proto/orders/v1;ordersv1b\x06proto3"

var (
	file_guide_proto_orders_v1_orders_proto_rawDescOnce sync.Once
	file_guide_proto_orders_v1_orders_proto_rawDescData []byte
)

func file_guide_proto_orders_v1_orders_proto_rawDescGZIP() []byte {
	file_guide_proto_orders_v1_orders_proto_rawDescOnce.Do(func() {
		file_guide_proto_orders_v1_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guide_proto_orders_v1_orders_proto_rawDesc), len(file_guide_proto_orders_v1_orders_proto_rawDesc)))
	})
	return file_guide_proto_orders_v1_orders_proto_rawDescData
}

var file_guide_proto_orders_v1_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guide_proto_orders_v1_orders_proto_goTypes = []any{
	(*Place)(nil),  // 0: orders.v1.Place
	(*Placed)(nil), // 1: orders.v1.Placed
}
var file_guide_proto_orders_v1_orders_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guide_proto_orders_v1_orders_proto_init() }
func file_guide_proto_orders_v1_orders_proto_init() {
	if File_guide_proto_orders_v1_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guide_proto_orders_v1_orders_proto_rawDesc), len(file_guide_proto_orders_v1_orders_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_guide_proto_orders_v1_orders_proto_goTypes,
		DependencyIndexes: file_guide_proto_orders_v1_orders_proto_depIdxs,
		MessageInfos:      file_guide_proto_orders_v1_orders_proto_msgTypes,
	}.Build()
	File_guide_proto_orders_v1_orders_proto = out.File
	file_guide_proto_orders_v1_orders_proto_goTypes = nil
	file_guide_proto_orders_v1_orders_proto_depIdxs = nil
}
