// grpcproc.pubsub.v1 is what grpcproc/pubsub's topics are called with, and
// what they tell the process that asked to be notified.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: grpcproc/pubsub/v1/pubsub.proto

package pubsubv1

import (
	v1 "github.com/floatdrop/grpcproc/proto/grpcproc/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Subscribe, as a call, adds the caller to a topic. The topic sends it the
// events it keeps first, then answers with Subscribed; every event published
// after that follows, in order.
type Subscribe struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time left to the caller, for a relay that has to subscribe to its
	// topic first: it gives up when the caller does. Unset: no limit.
	Timeout       *durationpb.Duration `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribe) Reset() {
	*x = Subscribe{}
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribe) ProtoMessage() {}

func (x *Subscribe) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribe.ProtoReflect.Descriptor instead.
func (*Subscribe) Descriptor() ([]byte, []int) {
	return file_grpcproc_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{0}
}

func (x *Subscribe) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// Subscribed answers Subscribe.
type Subscribed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The process the events come from: the topic, or the relay on the
	// subscriber's node that stands in for a topic of another node.
	From *v1.PID `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	// How many of the last events the topic keeps, for a relay to keep as many.
	Buffer uint32 `protobuf:"varint,2,opt,name=buffer,proto3" json:"buffer,omitempty"`
	// The full name of the message type the topic publishes, or empty when
	// its events are of an interface type, for the subscriber to check.
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscribed) Reset() {
	*x = Subscribed{}
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscribed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscribed) ProtoMessage() {}

func (x *Subscribed) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscribed.ProtoReflect.Descriptor instead.
func (*Subscribed) Descriptor() ([]byte, []int) {
	return file_grpcproc_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{1}
}

func (x *Subscribed) GetFrom() *v1.PID {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Subscribed) GetBuffer() uint32 {
	if x != nil {
		return x.Buffer
	}
	return 0
}

func (x *Subscribed) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Unsubscribe, sent, removes the sender from a topic.
type Unsubscribe struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unsubscribe) Reset() {
	*x = Unsubscribe{}
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unsubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unsubscribe) ProtoMessage() {}

func (x *Unsubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unsubscribe.ProtoReflect.Descriptor instead.
func (*Unsubscribe) Descriptor() ([]byte, []int) {
	return file_grpcproc_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{2}
}

// Demand tells the process a topic notifies whether anyone subscribes: it
// is sent when the first subscriber comes and when the last one leaves.
type Demand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Demand) Reset() {
	*x = Demand{}
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Demand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Demand) ProtoMessage() {}

func (x *Demand) ProtoReflect() protoreflect.Message {
	mi := &file_grpcproc_pubsub_v1_pubsub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Demand.ProtoReflect.Descriptor instead.
func (*Demand) Descriptor() ([]byte, []int) {
	return file_grpcproc_pubsub_v1_pubsub_proto_rawDescGZIP(), []int{3}
}

func (x *Demand) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

var File_grpcproc_pubsub_v1_pubsub_proto protoreflect.FileDescriptor

const file_grpcproc_pubsub_v1_pubsub_proto_rawDesc = "" +
	"\n" +
	"\x1fgrpcproc/pubsub/v1/pubsub.proto\x12\x12grpcproc.pubsub.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1agrpcproc/v1/grpcproc.proto\"@\n" +
	"\tSubscribe\x123\n" +
	"\atimeout\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"^\n" +
	"\n" +
	"Subscribed\x12$\n" +
	"\x04from\x18\x01 \x01(\v2\x10.grpcproc.v1.PIDR\x04from\x12\x16\n" +
	"\x06buffer\x18\x02 \x01(\rR\x06buffer\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\r\n" +
	"\vUnsubscribe\"(\n" +
	"\x06Demand\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribedBAZ?github.com/floatdrop/grpcproc/proto/grpcproc/pubsub/v1;pubsubv1b\x06proto3"

var (
	file_grpcproc_pubsub_v1_pubsub_proto_rawDescOnce sync.Once
	file_grpcproc_pubsub_v1_pubsub_proto_rawDescData []byte
)

func file_grpcproc_pubsub_v1_pubsub_proto_rawDescGZIP() []byte {
	file_grpcproc_pubsub_v1_pubsub_proto_rawDescOnce.Do(func() {
		file_grpcproc_pubsub_v1_pubsub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpcproc_pubsub_v1_pubsub_proto_rawDesc), len(file_grpcproc_pubsub_v1_pubsub_proto_rawDesc)))
	})
	return file_grpcproc_pubsub_v1_pubsub_proto_rawDescData
}

var file_grpcproc_pubsub_v1_pubsub_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_grpcproc_pubsub_v1_pubsub_proto_goTypes = []any{
	(*Subscribe)(nil),           // 0: grpcproc.pubsub.v1.Subscribe
	(*Subscribed)(nil),          // 1: grpcproc.pubsub.v1.Subscribed
	(*Unsubscribe)(nil),         // 2: grpcproc.pubsub.v1.Unsubscribe
	(*Demand)(nil),              // 3: grpcproc.pubsub.v1.Demand
	(*durationpb.Duration)(nil), // 4: google.protobuf.Duration
	(*v1.PID)(nil),              // 5: grpcproc.v1.PID
}
var file_grpcproc_pubsub_v1_pubsub_proto_depIdxs = []int32{
	4, // 0: grpcproc.pubsub.v1.Subscribe.timeout:type_name -> google.protobuf.Duration
	5, // 1: grpcproc.pubsub.v1.Subscribed.from:type_name -> grpcproc.v1.PID
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpcproc_pubsub_v1_pubsub_proto_init() }
func file_grpcproc_pubsub_v1_pubsub_proto_init() {
	if File_grpcproc_pubsub_v1_pubsub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpcproc_pubsub_v1_pubsub_proto_rawDesc), len(file_grpcproc_pubsub_v1_pubsub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_grpcproc_pubsub_v1_pubsub_proto_goTypes,
		DependencyIndexes: file_grpcproc_pubsub_v1_pubsub_proto_depIdxs,
		MessageInfos:      file_grpcproc_pubsub_v1_pubsub_proto_msgTypes,
	}.Build()
	File_grpcproc_pubsub_v1_pubsub_proto = out.File
	file_grpcproc_pubsub_v1_pubsub_proto_goTypes = nil
	file_grpcproc_pubsub_v1_pubsub_proto_depIdxs = nil
}
